# Generated by Django 5.2 on 2025-04-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_car_create_date_alter_car_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
