# Generated by Django 5.2 on 2025-04-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_car_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_image',
        ),
    ]
